---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    driver:
      provider: vmware_workstation
  - name: centos-7.3
    driver:
      provider: vmware_workstation
  - name: fedora-25
    driver:
      provider: vmware_workstation
  - name: debian-8.7
    driver:
      provider: vmware_workstation

suites:
  - name: default
    run_list:
      - recipe[zerotier::install]
      - recipe[zerotier::ohai_plugin]
      - recipe[zerotier::join_networks]
    #verifier:
    #  inspec_tests:
    #    - test/smoke/install
    attributes:
